apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-latency-server
  namespace: node-latency
  labels:
    app: node-latency-server
spec:
  selector:
    matchLabels:
      app: node-latency-server
  template:
    metadata:
      labels:
        app: node-latency-server
    spec:
      containers:
        - name: server-container
          image: jaehnri/node-latency-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 8080
