apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-latency-server
  namespace: node-latency
  labels:
    app: node-latency-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-latency-server
  template:
    metadata:
      labels:
        app: node-latency-server
    spec:
      containers:
        - name: server-container
          image: node-latency-server:test
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
            - containerPort: 8080
          env:
            - name: KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
