apiVersion: v1
kind: Service
metadata:
  name: node-latency-server-service
  namespace: node-latency
spec:
  selector:
    app: node-latency-server
  ports:
    - name: tcp-endpoint
      port: 3000
      targetPort: 3000
    - name: http-endpoint
      port: 8080
      targetPort: 8080
