apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server-label
  ports:
    - name: tcp-endpoint
      port: 3000
      targetPort: 3000
    - name: http-endpoint
      port: 8080
      targetPort: 8080
  type: ClusterIP
