kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-latency-client-cluster-role-binding
  namespace: node-latency
subjects:
  - kind: ServiceAccount
    name: node-latency-client-service-account
    namespace: node-latency
roleRef:
  kind: ClusterRole
  name: node-latency-client-cluster-role
  apiGroup: rbac.authorization.k8s.io
