apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-latency-client
  namespace: node-latency
  labels:
    app: node-latency-client
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: node-latency-client
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
      labels:
        app: node-latency-client
    spec:
      serviceAccountName: node-latency-client-service-account
      containers:
        - name: node-latency-client
          image: node-latency-client:test
          imagePullPolicy: Never
          env:
            - name: KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName