apiVersion: v1
kind: Service
metadata:
  name: node-latency-client-service
spec:
  selector:
    app: node-latency-client
  ports:
    - name: metrics-endpoint
      port: 8081
      targetPort: 8081
