apiVersion: v1
kind: Service
metadata:
  name: node-latency-server-service
  labels:
    {{- include "node-latency.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp-endpoint
      port: 3000
      targetPort: 3000
    - name: http-endpoint
      port: 8080
      targetPort: 8080
  selector:
    {{- include "node-latency.selectorLabels" . | nindent 4 }}
